#!/usr/bin/env python3
"""Discover and assign fixed USB camera ports without opening both streams together."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import glob
import json
import os
from pathlib import Path
import subprocess
import sys
from typing import Any


def udev_properties(device: str) -> dict[str, str]:
    try:
        output = subprocess.check_output(
            ["udevadm", "info", "--query=property", f"--name={device}"], text=True, stderr=subprocess.DEVNULL
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return {}
    values: dict[str, str] = {}
    for line in output.splitlines():
        key, separator, value = line.partition("=")
        if separator:
            values[key] = value
    return values


def discover() -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for by_path in sorted(glob.glob("/dev/v4l/by-path/*-video-index0")):
        real_device = os.path.realpath(by_path)
        props = udev_properties(real_device)
        records.append(
            {
                "by_path": by_path,
                "real_device": real_device,
                "id_path": props.get("ID_PATH", Path(by_path).name.removesuffix("-video-index0")),
                "serial": props.get("ID_SERIAL_SHORT", ""),
                "vendor_id": props.get("ID_VENDOR_ID", ""),
                "model_id": props.get("ID_MODEL_ID", ""),
                "model": props.get("ID_MODEL", ""),
            }
        )
    return records


def validate_assignment(left: dict[str, Any], right: dict[str, Any]) -> None:
    if os.path.realpath(str(left["real_device"])) == os.path.realpath(str(right["real_device"])):
        raise ValueError("left and right camera resolve to the same video device")
    if str(left.get("id_path", "")) == str(right.get("id_path", "")):
        raise ValueError("left and right camera have the same physical ID_PATH")


def test_snapshot(device: str) -> None:
    command = [
        "v4l2-ctl", "--device", device, "--stream-mmap=3", "--stream-count=1", "--stream-to=/dev/null"
    ]
    try:
        subprocess.run(command, check=True, timeout=8, stdout=subprocess.DEVNULL)
    except FileNotFoundError as exc:
        raise RuntimeError("v4l2-ctl is required for sequential camera validation") from exc
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        raise RuntimeError(f"camera snapshot failed: {device}") from exc


def select_record(records: list[dict[str, Any]], path: str) -> dict[str, Any]:
    requested = os.path.realpath(path)
    for record in records:
        if record["by_path"] == path or os.path.realpath(str(record["real_device"])) == requested:
            return record
    raise ValueError(f"camera is not a discovered by-path capture node: {path}")


def atomic_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def update_config(config_path: Path) -> None:
    if not config_path.is_file():
        return
    data = json.loads(config_path.read_text(encoding="utf-8"))
    data["cameras"]["left"]["camera_device"] = "/dev/smartbag-camera-left"
    data["cameras"]["right"]["camera_device"] = "/dev/smartbag-camera-right"
    data["snapshot_classifier"]["left_device"] = "/dev/smartbag-camera-left"
    data["snapshot_classifier"]["right_device"] = "/dev/smartbag-camera-right"
    atomic_json(config_path, data)


def rules_text(data: dict[str, Any]) -> str:
    lines = ["# Generated by SmartBag camera-udev-install.sh; match physical USB port and capture index 0."]
    for side in ("left", "right"):
        id_path = str(data[side].get("id_path", ""))
        if not id_path:
            raise ValueError(f"missing ID_PATH for {side} camera")
        if '"' in id_path or "\n" in id_path:
            raise ValueError("unsafe ID_PATH in hardware discovery data")
        lines.append(
            f'SUBSYSTEM=="video4linux", ATTR{{index}}=="0", ENV{{ID_PATH}}=="{id_path}", '
            f'SYMLINK+="smartbag-camera-{side}"'
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    discover_parser = subparsers.add_parser("discover")
    discover_parser.add_argument("--output", type=Path)
    assign_parser = subparsers.add_parser("assign")
    assign_parser.add_argument("--left", required=True)
    assign_parser.add_argument("--right", required=True)
    assign_parser.add_argument("--output", type=Path, default=Path("/etc/smartbag/hardware-discovery.json"))
    assign_parser.add_argument("--config", type=Path, default=Path("/etc/smartbag/config.json"))
    assign_parser.add_argument("--skip-snapshot-test", action="store_true")
    rules_parser = subparsers.add_parser("rules")
    rules_parser.add_argument("--discovery", type=Path, default=Path("/etc/smartbag/hardware-discovery.json"))
    rules_parser.add_argument("--output", type=Path, default=Path("/etc/udev/rules.d/99-smartbag-cameras.rules"))
    args = parser.parse_args()

    try:
        records = discover()
        if args.command == "discover":
            result = {"generated_at": datetime.now(timezone.utc).isoformat(), "cameras": records}
            if args.output:
                atomic_json(args.output, result)
            print(json.dumps(result, ensure_ascii=False, indent=2))
            return 0
        if args.command == "assign":
            left = select_record(records, args.left)
            right = select_record(records, args.right)
            validate_assignment(left, right)
            if not args.skip_snapshot_test:
                test_snapshot(str(left["by_path"]))
                test_snapshot(str(right["by_path"]))
            result = {
                "schema_version": 1,
                "assigned_at": datetime.now(timezone.utc).isoformat(),
                "capture_policy": "alternating; never STREAMON both devices together",
                "left": left,
                "right": right,
            }
            atomic_json(args.output, result)
            update_config(args.config)
            print(json.dumps(result, ensure_ascii=False, indent=2))
            return 0
        data = json.loads(args.discovery.read_text(encoding="utf-8"))
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rules_text(data), encoding="utf-8", newline="\n")
        print(args.output)
        return 0
    except (KeyError, OSError, RuntimeError, ValueError, json.JSONDecodeError) as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
